version: "3"

services:
  mysql-master:
    image: mysql:latest
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
      MYSQL_USER: "slave"
      MYSQL_PASSWORD: "123"
    ports:
      - 4406:3306
    networks:
      - my_network
    volumes: 
      - ./schemas:/var/lib/mysql

  mysql-slave:
    image: mysql:latest
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: "toor"
    ports:
      - 5506:3306
    networks:
      - my_network

networks:
  my_network:
    driver: bridge